export const ApiEndpoints = {
  login: () => `v1/login`,
  forgotPassword: () => `v1/forgotPassword`,
  profileData: () => `v1/profiles`,
  subscription: (id: any) => `v1/subcription/save/${id}`,
  signUpStage1: () => `v1/sign-up/stage1`,
  signUpStage2: () => `v1/sign-up/stage2`,
  signUpStage3: () => `v1/sign-up/stage3`,
  createNew: () => `v1/file/validation`,              /*  file validation api*/
  fileValidation: () => `v1/file/validation`,              /*  file validation api*/
  fileDataValidation: () => `file/data-validation/check`,              /*  file data validation check api*/
  fileDuplicateCheck: () => `file/data-duplicate/check`, 
  dataDuplicateCheckByReconId: (id:string) => `file/data-duplicate/check/${id}`,   /*  file duplicate check api*/
  fileDataValidationByReconId: (id: string) => `file/data-validation/check/recon/${id}`, 
  changeProfilePassword: () => `v1/profiles/changepassword`,
  addUser: () => `v1/appusers`,
  getUserId: () => `v1/appusers/`,
  deleteUserId: (id: string) => `v1/appusers/${id}`,
  userList: () => `v1/appusers`,
  getPrivilages: () => `v1/profiles/getprivilages`,
  client: () => `v1/client`,
  reconbyId: (id: string)  => `v1/operation/recon/clientid/${id}`,
  recon: () => 'v1/recon',
  gstr9: () => `gstr9`,
  auditLogs: (page: number, searchKey: string) => `v1/auditlogs?start=${page}&length=10&columns[0][data]=user&columns[0][search][value]=${searchKey}`,
  resetPassword: () => `v1/firstlogin`,
  plan: () => `v1/plan`,
  reconAdd: () => `v1/operation/recon`,
  uploadDocument: () => `v1/fileupload/upload`,
  fileUploads: () => `upload-file`,
  notification: () => `v1/uinotifications?`,
  subscriber: () => `v1/subscriber`,
  executionRecon: () => `executionrecon`,
  getUserProfile: (id: string) => `v1/appusers/${id}`,
  getAllSubscriptions: () => `v1/subcription/getall`,
  fileValidationByReconId: () => `v1/file/validation/recon/`,
  gstrTransaction: () => `v1/gstr?page=1`,
  submitReview: () => `v1/reconmatching`,
  submitReviewUnmatch: () => `v1/reconunmatching`,
  itcTransaction: () => `v1/itc?page=1`,
  updateItcData: () => `v1/itc`,
  updateIncorrectITCData: () => `v1/invalid-itc`,
  updateGSTRData: () => `v1/gstr`,
  updateIncorrectGSTRData: () => `v1/invalid-gstr`,
  itcFilterTransaction: (query: string) => `v1/itc/filter?${query}`,  
  getDashboardData: () => `v1/dashboard`,
  getSupplierDashboard: () => `v1/dashboard/supplierdashboard`,
  supplierrecondashboard: () => `v1/dashboard/supplierrecondashboard`,
  yearlyrecondashboard: () => `v1/yearly-dashboard/`,
  monthlyrecondashboard: () => `v1/monthly-dashboard/`,
  downloadRecons : () => `v1/download/recon`,
  roles: () => `v1/roles`,
  getPreviligs: () => `v1/privileges`,
  gstrFilterTransaction: (query: string) => `v1/gstr/filter?${query}`,
  gstrExportTransaction: () => `v1/gstr/export-transaction`,
  itcExportTransaction: () => `v1/itc/export-transaction`,
  executionreconCount: (id: number) => ``,
  transistionUnMatch: (file: any) => `v1/reconmatching/3?fileType=${file}`,
  reconmatching: () => `v1/reconmatching`,
  clientStatus: () => `v1/commondashboard/clientstatus`,
  totalCount: () => `v1/commondashboard/totalcount`,
  commonDashboardMismatchRecon:(page:number)=> `v1/commondashboard/mismatchrecon?start=0&length=${page}`,
  commonDashboardMismatchClientWise:(page:number)=> `v1/commondashboard/mismatchclientwise?start=0&length=${page}`,
  pendingRecon: (page: number) => `v1/commondashboard/pendingrecon?start=${page}&length=10`,
  pendingReconClientWise: (page: number) => `v1/commondashboard/reconclientwise?start=${page}&length=10`,
  getProfile:()=> `v1/profiles?OperationType=UpdateProfileImage`,
  addRules:()=>`v1/rules`,
  downloadFileExportes : () => `v1/download/file/exported?maxResults=5&seen=0`,
  getAdminDashboardData:()=>`v1/homedashboard/`,
  passwordPolicy:()=>`v1/passwordpolicies`,
  getAllColums: ()=> `v1/columns`,
  getRules: () => `v1/rules`,
  suplierDashboard:()=> `v1/suppliers-dashboard`,
  getReonsByClientId: (clientId: string) => `v1/operation/recon/clientid/${clientId}`,
  getRuleListByReconId: (reconId: string) => `v1/record/matching/recon/${reconId}`,
  getPreviligsByRole: (roleId: string) => `v1/roles/byRole/${roleId}`,
  updatePrivilege: () => `v1/roles?Operation=UpdatePrivilege`,
  getManualMatchGSTR2BData: (id: any) => `v1/manualmatch/execution/getgstr2b/${id}`,
  getManualMatchITCData: (id: number) => `v1/manualmatch/execution/getitc/${id}`,
  acceptManualMatchData: () => `v1/manualmatch/execution/accept`,
  recordMatching:(id:any) => `v1/record/matching/recon/${id}`,
  rejectManualMatchData: () => `v1/manualmatch/execution/reject`,
  saveRecordingMatching: () => `v1/record/matching`,
  getAllOperator: () => `v1/operator`,
  getProfilePriviligs: () => `v1/privileges?Find=ByRole`,
  getReconsByClientId: (id: any) => `v1/operation/recon/clientid/${id}`,
  getInvalidGstrTrans: (query: string) => `v1/invalid-gstr/filter?${query}`,
  getItcInvalidTrans: (query: string) => `v1/invalid-itc/filter?${query}`,
  manualMatch: () => `v1/manual-match`,
  subscriptionSave: () => `v1/subcription/save-tenant`,
  getGSTRDataByReconId: () => `v1/loadgstr2b`,
  getITCDataByReconId: () => `v1/loaditc`,
  getReconOperationByExecutionId: () => `v1/reconoperations`,
  discardInvalidGstr: () => `v1/invalid-gstr`,
  discardInvalidItc: () => `v1/invalid-itc`,
};
